info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 首页
  /login:
    post:
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: code","massage"}
          schema:
            type: string
      summary: 登录
      tags:
      - 登录
  /user:
    delete:
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: code","massage"}
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户
    get:
      responses:
        "200":
          description: code","massage"}
          schema:
            type: string
      summary: 用户列表
      tags:
      - 用户
    post:
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 确认密码
        in: formData
        name: repassword
        required: true
        type: string
      - description: 手机号
        in: formData
        name: phone
        required: true
        type: string
      responses:
        "200":
          description: code","massage"}
          schema:
            type: string
      summary: 添加用户
      tags:
      - 用户
    put:
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      - description: 用户名
        in: formData
        name: username
        type: string
      - description: 密码
        in: formData
        name: password
        type: string
      - description: 手机号
        in: formData
        name: phone
        type: string
      - description: 邮箱
        in: formData
        name: email
        type: string
      responses:
        "200":
          description: code","massage"}
          schema:
            type: string
      summary: 修改用户
      tags:
      - 用户
swagger: "2.0"
